id = "openstudier"
name = "OpenStudier"
description = "The open source coding agent."
version = "1.2.25"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/GamblerIX/OpenStudier"

[agent_servers.openstudier]
name = "OpenStudier"
icon = "./icons/openstudier.svg"

[agent_servers.openstudier.targets.darwin-aarch64]
archive = "https://github.com/GamblerIX/OpenStudier/releases/download/v1.2.25/openstudier-darwin-arm64.zip"
cmd = "./openstudier"
args = ["acp"]

[agent_servers.openstudier.targets.darwin-x86_64]
archive = "https://github.com/GamblerIX/OpenStudier/releases/download/v1.2.25/openstudier-darwin-x64.zip"
cmd = "./openstudier"
args = ["acp"]

[agent_servers.openstudier.targets.linux-aarch64]
archive = "https://github.com/GamblerIX/OpenStudier/releases/download/v1.2.25/openstudier-linux-arm64.tar.gz"
cmd = "./openstudier"
args = ["acp"]

[agent_servers.openstudier.targets.linux-x86_64]
archive = "https://github.com/GamblerIX/OpenStudier/releases/download/v1.2.25/openstudier-linux-x64.tar.gz"
cmd = "./openstudier"
args = ["acp"]

[agent_servers.openstudier.targets.windows-x86_64]
archive = "https://github.com/GamblerIX/OpenStudier/releases/download/v1.2.25/openstudier-windows-x64.zip"
cmd = "./openstudier.exe"
args = ["acp"]
