name: openstudier

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  openstudier:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /openstudier') ||
      startsWith(github.event.comment.body, '/openstudier')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run openstudier
        uses: GamblerIX/OpenStudier/github@latest
        env:
          OPENSTUDIER_API_KEY: ${{ secrets.OPENSTUDIER_API_KEY }}
          OPENSTUDIER_PERMISSION: '{"bash": "deny"}'
        with:
          model: openstudier/claude-opus-4-5
